spring.application.name=security
server.port=8081

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/pdf_automation
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#JWT utilities
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

# Kafka JSON Configuration

spring.kafka.bootstrap-servers=localhost:9092

# Producer JSON serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer JSON deserializer
spring.kafka.consumer.group-id=spring-pdf-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Allow JSON for all packages (important)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Parallel consumers
spring.kafka.listener.concurrency=3

# Upload File Path
application.file.upload-dir=${UPLOAD_PATH:./uploads/}